export const ActionTypes = {
    GET_QUERY_RESULTS_PENDING: 'GET_QUERY_RESULTS_PENDING',
    GET_QUERY_RESULTS_COMPLETED: 'GET_QUERY_RESULTS_COMPLETED',
    GET_QUERY_RESULTS_FAILED: 'GET_QUERY_RESULTS_FAILED',
}